# Site
github: [metadata]
repository: changgyu-ryu/changgyu-ryu.github.io
# favicon: images/favicon.ico

# Personal info
name: 류창규
title: 백엔드 엔지니어
email: ckue21@gmail.com
website: https://velog.io/@micaelknife

# Social links
# twitter_username: changgyu-ryu
github_username: changgyu-ryu
# dribbble_username: jekyll
# facebook_username: changgyu-ryu
# flickr_username: jekyll
# linkedin_username: changgyu-ryu
# pinterest_username: jekyll
# youtube_username: UCSEOUzkGNCT_29EU_vnBYjg

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 <mark>4년차</mark> **백엔드 개발자**로, **중앙부처 및 공공기관을 위한 대규모 정보시스템 구축 프로젝트에서 설계, 개발, 운영 경험**을 쌓았습니다. 
  특히 <mark>차세대 사회보장정보시스템 구축 사업</mark>에 참여하여 **복잡한 비즈니스 로직**을 구현하고, 
  **대용량 데이터를 효율적으로 처리하는 기술**을 습득했습니다.
  코드의 품질과 시스템의 안정성을 중요하게 생각하여 <mark>테스트 코드</mark> 작성과 코드 리뷰를 주도적으로 진행해왔습니다. 
  <mark>디지털서비스플랫폼 개발 지원</mark>을 위해 **대전에 6개월 동안 투입**되어 병무청 API 연계를 위해 <mark>PL</mark>로서 수행한 경험이 있으며,
  '24년 6월에 <mark>서비스 오픈</mark>과 8월에 <mark>고도화 전환</mark>까지 성공적으로 수행했습니다.
  또한, 새로운 기술 습득에 대한 열정으로 RESTful API 개발, 성능 최적화,
  그리고 **Javascript, React, Typescript, React** 등 프론트엔드 기술에 관심을 가지고 학습하고 있습니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Certification Section
# certification_title: Certification
certification_content: |
  - 정보처리기사 (2015.10)
  - OPIC IM2
  - TOEIC 880
  - 공군 중위 전역 (정보통신, 2016.02 - 2019.05)

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  여러 기술 스택에 관심을 갖고 개인 프로젝트를 수행했습니다.
   - [OMDb API 영화 찾기 홈페이지](https://github.com/ChangGyu-Ryu/vanillajs-movie-app): HTML, CSS, JavaScript, TypeScript를 활용한 OMDb API 영화 찾기 홈페이지 구현 [DEMO](https://vanillajs-movie-app-peach.vercel.app/#/)
   - [아이패드 제품 페이지](https://github.com/ChangGyu-Ryu/apple-ipad-app): HTML, CSS, JavaScript를 활용한 아이패드 제품 페이지 구현 [DEMO](https://apple-ipad-app-liart.vercel.app/)
   - [스타벅스 홈페이지](https://github.com/ChangGyu-Ryu/starbucks-vanila-app): HTML, CSS, JavaScript를 활용한 스타벅스 홈페이지 구현 [DEMO](https://spiffy-jalebi-958ea7.netlify.app/)
   - [오버워치 캐릭터 선택 화면](https://github.com/ChangGyu-Ryu/overwatch-hero-selector): HTML, CSS를 활용한 오버워치 캐릭터 선택 화면 구현 [DEMO](https://main--overwatch-selector-hero.netlify.app/)
   - [게시판 서비스](https://github.com/ChangGyu-Ryu/fastcampus-project-board): Spring Boot 3.2.2 기반의 게시판 서비스
   - [게시판 관리자 서비스](https://github.com/ChangGyu-Ryu/fastcampus-project-board-admin): Spring Boot 3.2.2 기반의 게시판 관리 도구

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
